### ISSUE TITLE
ImportError: No module named waveshare_library.epd2in7

### ISSUE THREAD

**Issue by corq** [lyoko17220/ePaperLibrary#1]
Where is the waveshare_library.epd2in7 module located? Thanks!

/opt/ePaperLibrary# python epsimplelib.py
Traceback (most recent call last):
  File "epsimplelib.py", line 9, in <module>
    import waveshare_library.epd2in7
ImportError: No module named waveshare_library.epd2in7

**Comment by nsagot** [comment]
Hi, waveshare_library is folder and in this folder there is epd2in7 file.

Have you imported all the repository with the same folder structure ?

**Comment by ktinkerer** [comment]
I had the same issue and solved it by creating a blank file named '__init__.py' in the waveshare_library folder. Works great now!

**Comment by nsagot** [comment]
I will push a update to resolve the problem. Thanks for your report !
